version: 2.1
jobs:
  build:
    docker:
      - image: johannesloetzsch/nix-flake:latest
    steps:
      - run:
          name: Disable Sandbox
          command: mkdir -p ~/.config/nix/; echo 'sandbox = false' > ~/.config/nix/nix.conf;
      - checkout
      - restore_cache:
          keys:
            - nix-{{ checksum "flake.lock" }}-{{ checksum "flake.nix" }}
            - nix
      - run: nix build .#example-clj-lein
      - save_cache:
          key: nix-{{ checksum "flake.lock" }}-{{ checksum "flake.nix" }}
          paths:
            - /nix/
  test:
    docker:
      - image: johannesloetzsch/nix-flake:latest
    steps:
      - run:
          name: Disable Sandbox
          command: mkdir -p ~/.config/nix/; echo 'sandbox = false' > ~/.config/nix/nix.conf;
      - checkout
      - restore_cache:
          keys:
            - nix-{{ checksum "flake.lock" }}-{{ checksum "flake.nix" }}
            - nix
      - run: nix run .#example-clj-lein
workflows:
  version: 2
  build+test:
    jobs:
      - build
      - test:
          requires:
            - build
