version: 2.1
jobs:
  build:
    docker:
      - image: johannesloetzsch/nix-flake:latest
    steps:
      - run:
          name: Disable Sandbox
          command: mkdir -p ~/.config/nix/; echo 'sandbox = false' >> ~/.config/nix/nix.conf;
      - run:
          name: Allow qemu to be used in dockerTools.buildImage.runAsRoot
          command: mkdir -p ~/.config/nix/; echo 'system-features = kvm' >> ~/.config/nix/nix.conf;
      - checkout
      - restore_cache:
          keys:
            - nix-{{ checksum "flake.lock" }}-{{ checksum "flake.nix" }}
            - nix
      - run: nix build .#flake-docker
      - run: nix build .#example-clj-lein
      - run: nix build .#example-clj-lein-docker
      - save_cache:
          key: nix-{{ checksum "flake.lock" }}-{{ checksum "flake.nix" }}
          paths:
            - /nix/
  test:
    docker:
      - image: johannesloetzsch/nix-flake:latest
    steps:
      - run:
          name: Disable Sandbox
          command: mkdir -p ~/.config/nix/; echo 'sandbox = false' >> ~/.config/nix/nix.conf;
      - checkout
      - restore_cache:
          keys:
            - nix-{{ checksum "flake.lock" }}-{{ checksum "flake.nix" }}
            - nix
      - run: nix run .#example-clj-lein
  deploy:
    docker:
      - image: johannesloetzsch/nix-flake:latest
    steps:
      - run:
          name: Disable Sandbox
          command: mkdir -p ~/.config/nix/; echo 'sandbox = false' >> ~/.config/nix/nix.conf;
      - checkout
      - restore_cache:
          keys:
            - nix-{{ checksum "flake.lock" }}-{{ checksum "flake.nix" }}
            - nix
      - run: nix run .#deploy
workflows:
  version: 2
  build+test+deploy:
    jobs:
      - build:
          filters:  # tags+branches
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:  # tags+branches
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:  # tags only
            tags:
              only: /.*/
            branches:
              ignore: /.*/
